### ISSUE TITLE
Distributed memeory and interface with scalapack/elpa

### ISSUE THREAD

**Issue by sangallidavide** [yambo-code/yambo#113]
@muralidhar-nalabothula prepared an interface to the scalapack/elpa which distributes the matrix in memory.

The code is in the form of a c-library here:
https://github.com/muralidhar-nalabothula/Ydiago

There is also the example of a fortran interface:
https://github.com/muralidhar-nalabothula/Ydiago/blob/main/src/fortran_interface/ydiago_interface.F

@andrea-ferretti we should have a look and discuss how to integrate this in yambo.
Do we prefer to compale the c-library and link it, or to integrate it directly inside the yambo code?

@muralidhar-nalabothula any further comment, beyond the discussion we had, is welcome.

**Comment by sangallidavide** [comment]
I add few comments.

The idea here is convert the BSE matrix from the "yambo distribution" (used to build the kernel, to the blacs/scalapack or elpa distribution. There are also some optimization for BSE matrices beyond TDA. All is potentially done on the fly (e.g. without the need of I/O), and without memory duplication, which is the main bottleneck in yambo at present.

**Comment by muralidhar-nalabothula** [comment]
I already wrote the Yambo interface. I added two new files:
subroutine for filling the scalapack matrix:
https://github.com/muralidhar-nalabothula/yambo/blob/master/src/bse/K_fill_block_cyclic.F

And a very general diagonalization function to be called from K_diago_driver.F that takes care of every thing.
https://github.com/muralidhar-nalabothula/yambo/blob/master/src/bse/K_diagonalize.F

@sangallidavide  I also fixed numerical instabilities of parallel general eigensolver (so the library should deal all cases and libelemental is not needed)

I tested the code and works wonderfully. I still haven't figured out how to distribute eigenvectors.

There are two options for eigenvector distributions:
1) Distribute eigenstates i.e every process get sub-set of full eigenvectors (This is what is the my implementation)
2) Distribute e-h basis (I am thinking of switching to this as it is more robust: nicely divides memory, and more over we need very minimal changes to the most of the residual subroutines (an additionally call to mpi_reduce in the end))

Let me know what you think.

I will leave to you guys how to embed the c code in Yambo as I am fine with any.

**Comment by sangallidavide** [comment]
Thanks @muralidhar-nalabothula 

When you think the two files are ready, con you open a pull request towards branch tech-master (yeah, the branch naming is terrible ... ). I'll later fix the linking. As I said, I'll probably have time to work on this in September.

For now the goal of this issue is the make the other developers aware of the present development, and to start the discussion on how to link the c-code.

For the distribution I do not have any specific comment for now.  Both options sounds fine with me.

**Comment by sangallidavide** [comment]
Dear Murali, an update after discussing with @andrea-ferretti which is the best strategy to import this in yambo.

What we plan to do is :
(i) to mirror your Ydiago repo inside the yambo organization
(ii) create a tag, in order to have a .tar.gz file to be downloaded (something like version 0.1.0 or similar, suggestions are welcome)
(iii) compile it as a library and link it, with the yambo configure filling the make.inc file (The last point is similar to how we compile now the iotk library)

In this way, if you keep working on your repo, we can just sync our mirror. If in the future you will drop it, we will be able to modify it (if needed).

@muralidhar-nalabothula I just wait for your ok before proceeding with these steps. Step (i) and (ii) first.
For step (iii) I'd work on a branch on top of your yambo/master just to fix the compilation and linking.

**Comment by muralidhar-nalabothula** [comment]
Fine for me :). I can also transfer the repository to Yambo organization if you want and work on it by opening a PR. If you want to change the name of the library, let me know.

For the compilation, you can directly pass the Yambo flags to make.inc (they are exactly same, you need to add a flag for elpa (I use -DWITH_ELPA, if you want to use other, let me know. I can add it). I will turn on the GPU support a bit later as I do not have a gpu machine to test it.

**Comment by sangallidavide** [comment]
Fine with me to transfer the repo and work with PR. Do you have the proper permissions?

For the name, either Ydiago or Ydiago-bse, since we are doing something BSE specific.

For the ELPA flag I'd prefer `-D_ELPA` as we do with other libraries. Fine with me to work later on GPU support. As a first step the goal is to have a proper CPU implementation with distributed memory over MPI tasks.

**Comment by muralidhar-nalabothula** [comment]
I added ```-D_ELPA``` flag support. It looks like I can only transfer to my private organization. I would ideally like to transfer the repo but we can figure it out in the end :)

**Comment by sangallidavide** [comment]
I've invited you to join the yambo organization as a member. Try again after accepting the invitation. If this is not enough I'll later upgrade your status to manager

**Comment by muralidhar-nalabothula** [comment]
I still cannot. I transferred it to you. Maybe you can try transferring it to Yambo

**Comment by sangallidavide** [comment]
Done. Repo here: https://github.com/yambo-code/Ydiago

**Comment by sangallidavide** [comment]
I close this issue since it is fixed by pull request #117
