### ISSUE TITLE
Exciton amplitude in magnons

### ISSUE THREAD

**Issue by alexmoratalla** [yambo-code/yambo#115]
The printing of the exciton amplitudes of ypp for spin-flip calculations seems to have an issue. I report the BSE calculations for alpha and Spm, together with the amplitude of the first exciton (magnon). You can see that exciton is in positive energies but the magnon is centered at 0 with negative contributions.

<img width="620" alt="image" src="https://github.com/yambo-code/yambo-devel/assets/2931286/8f1b19e5-8453-4fe8-b96b-f8097ad476f9">

My impression is that the amplitudes should be kind of similar because the material has rather flat bands. I have checked the file
ypp/excitons/excitons_amplitude.F and in line 169 I find:

amp_trans(amp_n_trans,1)=Xen%E(ic,ikibz,i_spin)-Xen%E(iv,ikp,i_spin)

It seems is assigning the same spin for conduction and valence, but in the case of magnons it should have opposite spin.

I have also checked the file ypp/excitons/excitons_read.F and in line 117:
YAMBO_ALLOC(BSS_eh_table,(BS_H_dim,3+n_sp_pol-1))
it is not reading the spin polarization of conduction and valence band.

I have worked a bit and it seems a problem of the eigenvalues. I have check the eigenvalues and the conduction band states have lower values than the valence bands states. Still I haven't found a solution.

**Comment by sangallidavide** [comment]
This issue was affecting the branch phys-magnons in my personal fork.
It was fixed with this PR: https://github.com/sangallidavide/yambo/pull/1
I close it now
