### ISSUE TITLE
CUDA cusolverDnCgetrs failed

### ISSUE THREAD

**Issue by andreamarini** [yambo-code/yambo#120]
It looks like I am not able to run yambo with CUDA support.

Branch:gpl/master

```
>nvfortran -v
Export NVCOMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/24.1
```
When I launch the test-suite I get

```
 <---> Xo@q[1] |                                        | [000%] --(E) --(X)
 <---> Xo@q[1] |########################################| [100%] --(E) --(X)
 <---> [LA] X compute_on_gpu : yes


 <---> X@q[1] |                                        | [000%] --(E) --(X)
[ERROR] STOP signal received while in[05] Dynamic Dielectric Matrix (PPA)
[ERROR] LINEAR ALGEBRA driver [SERIAL_lin_system_gpu]cusolverDnCgetrs failed
```
This the same error the ROBOTS (mo and Eliud) produce.

Any help is welcome.

**Comment by sangallidavide** [comment]
This is the bug fixed quite some time ago. Fix not yet in the master because merges are blocked.

**Comment by andreamarini** [comment]
I have the same error with yoda/develop.

Which branch is bug-free?

**Comment by andreamarini** [comment]
Solved by entering

`/usr/lib/gcc/x86_64-linux-gnu`

and linking by hand the latest version (12) to 10

```
x86_64-linux-gnu>ls -lst
total 4
0 lrwxrwxrwx 1 root root    2 Aug  2 11:28 10 -> 12
4 drwxr-xr-x 5 root root 4096 Apr 22 09:51 12
```
In addition the test-suite works only by launching the NVIDIA robot with 1 cpu.
