### ISSUE TITLE
Yambo re-diagonalizes even when the ```ndb.BS_diago_Q1``` file is present.

### ISSUE THREAD

**Issue by sangallidavide** [yambo-code/yambo#140]
>  For some reason, when using the ydiago solver, Yambo re-diagonalizes even when the ```ndb.BS_diago_Q1``` file is present. I am not sure where the issue is coming from.

_Originally posted by @muralidhar-nalabothula in https://github.com/yambo-code/yambo/issues/127#issuecomment-2405547650_

**Comment by sangallidavide** [comment]
The issue is due to the following error when reading the ndb.BS_diago database
```
   *ERR* BS kernel          energies                : Teter 93(XC)
```
When writing the databse, after diagonalization, the value of the variable is
```
K_E_xc_string=Teter 93(XC)
```

However, when late reading it, the value is
```
K_E_xc_string=analytical correction @E
````

The change is due to the call `setup_global_XC --> in QP_apply`
```
call setup_global_XC(trim(QP_ctl_what),QP_SE_NONE,STRING=QP_ctl_xc_STRING)
```
where `QP_ctl_xc_STRING` was previously changed in
```
src/qp_control/QP_apply_the_ACTION.F:   QP_ctl_xc_STRING=trim(QP_ctl_xc_STRING)//" analytical correction "
```

**Comment by sangallidavide** [comment]
Issue is present also in branch maintenance-master

**Comment by sangallidavide** [comment]
Issue is due to 2 factors

a) merging `XC_WF_kind_IO` and `XC_E_kind_io` contained in `io_header` was at a certain point changed into a single subroutine: `XC_kind_io`
b) the new `XC_kind_io` used in writing mode always `loaded_WF_xc_string` while in reading mode, it always use the input `string`

The use of `loaded_WF_xc_string` does not make sense. As a consequence, one thing is written inside databases, while in reading mode a different variable is checked ...

**Comment by sangallidavide** [comment]
Tentive fix released

**Comment by andreamarini** [comment]
Last commit in maintenance-master introduced some further errors in the robots.

https://media.yambo-code.eu/robots/GPL/maintenance-master/mo.farah.4.php
