### ISSUE TITLE
make all seems broken

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [yambo-code/yambo#28]
Hello,

I am trying to compile Yambo 4.5.3 for a user but I am running into some issues when doing `make all`.

As far as I can tell, there are some issues with the "internal" dependencies handling in the makefile.

For example, `ypp` is compiled before `ypp_ph`. Both depends on `ypp/modules/` but `ypp_ph` adds a `YPP_ELPH` define when compiling the files in this folder. Unfortunately it seems that it doesn't trigger a new recompilation when the folder `ypp/modules/` has already been visited when building `ypp`.

Any ideas on how to fix that issue or at least work it around?

Best regards,
Rémi

**Comment by sangallidavide** [comment]
Dear Rémi, on my machine it works fine.

Do a "make clean_all" before and retry.

In case it does not work, could you open a discussion on the yambo forum:
[http://www.yambo-code.org/forum/viewforum.php?f=16](http://www.yambo-code.org/forum/viewforum.php?f=16)
Please attach there your `config/report file` and any useful info on the build there. We will address it there.

I close this for now.
In case any bug will be confirmed I'll reopen the issue.

**Comment by RemiLacroix-IDRIS** [comment]
I have opened a discussion on the forum: http://www.yambo-code.org/forum/viewtopic.php?p=9608#p9608.
