### ISSUE TITLE
Yambo 4.5.2: p2y issue (fmt error)

### ISSUE THREAD

**Issue by phz178387** [yambo-code/yambo#33]
Dear All,

While running the executable "p2y" for generating input files for Yambo using output files of Quantum Espresso, I encountered this error:

p2y

____    ____    ___      .___  ___.  .______     ______
\   \  /   /   /   \     |   \/   |  |   _  \   /  __  \
\   \/   /   /  ^  \    |  \  /  |  |  |_)  | |  |  |  |
 \_    _/   /  /_\  \   |  |\/|  |  |   _  <  |  |  |  |
   |  |    /  _____  \  |  |  |  |  |  |_)  | |  `--"  |
   |__|   /__/     \__\ |__|  |__|  |______/   \______/

<---> DBs path set to .
<---> detected QE data format: qexsd
<---> == PWscf v.6.x generated data (QEXSD fmt) ==
<---> Header/K-points/Energies...

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     Error in routine qexsd_read_symmetry (2):
    fmt problem

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     stopping ...
Abort(2) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 0

Below are some details of our installation :
QE 6.7 Intel MPI 2019 + intel mkl + fftw 3.3.8 + hdf5 1.10.4 (yambo 4.5.2 rev.171 - MPI+SLK)

@daniele-varsano @andrea-ferretti @andreamarini @sangallidavide

**Comment by daniele-varsano** [comment]
Dear, phz,
for these kind of issues we suggest to use the yambo forum:
http://www.yambo-code.org/forum/

Please see the answer poster there.
Best,
D.
