### ISSUE TITLE
nvfortran as PGI

### ISSUE THREAD

**Issue by osbama** [yambo-code/yambo#35]
Dear developers, 

I am trying to compile YAMBO with [NVIDIA HPC SDK 21.3](https://developer.nvidia.com/hpc-sdk) in order to benefit from GPUs in our cluster. The Fortran compiler bundled there identifies itself as *nvfortran*, however acts almost identical to *PGI* compiler. 

*PGI* compiler has some different ideas on how to interpret sources. I see workarounds for them are already implemented, i.e. in `src/modules/mod_stderr.F` with a preprocessor option `_PGI`  

Since `configure` does not recognize `nvfortran` as a *PGI* compiler, these workarounds are ignored.  

I suggest adding `nvfortran` to `config/m4/acx_get_fc_kind.m4` as a *PGI* compiler derivative

```m4
    *nvfortran*)
      FCKIND="pgi"
      FCVERSION=`$FC --version`
      ;;
``` 
Edit: 
It seems `acx_fortran_flags.m4` acts independently from `acx_get_fc_kind.m4`. *nvfortran* needs to be added there as well.

**Comment by sangallidavide** [comment]
Dear Osbma, thanks for reaching out.
Indeed  we did something similar in the develop (private) branch
```
  *nvfortran* )
    SYSFLAGS="-O2 -g -fast -Munroll -Mnoframe -Mdalign -Mbackslash"
    FUFLAGS="-O0 -Mbackslash"
    FCMFLAG="-Mnomain"
    OMPFLAGS="-mp"
    NETCDFFLAGS="-DpgiFortran"
    def_compiler="-D_PGI"
    DEBUG_FLAGS="-g -Minform=inform -Mbounds -Mchkptr -Mchkstk -Meh_frame -Mbackslash"
```
and we are working on something more refined on a dedicated branch.
We also fixed `acx_get_fc_kind.m4`

For release 5.0 I'll let the fix enter in the next patch.
