### ISSUE TITLE
Problem installing qe_pseudo

### ISSUE THREAD

**Issue by chrisreidy** [yambo-code/yambo#37]
In building yambo with ext-libs, I get an error
This is on a Centos7 server for our supercomputer.
>>>[Making qe_pseudo]<<<
cp: ‘/opt/ohpc/admin/UAbuild/yambo/yambo-5.0.3/lib/qe_pseudo/.objects’ and ‘lib/qe_pseudo/.objects’ are the same file
<command-line>: warning: ISO C99 requires whitespace after the macro name
make[2]: Entering directory `/opt/ohpc/admin/UAbuild/yambo/yambo-5.0.3/lib/qe_pseudo'
Makefile:104: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make[2]: Leaving directory `/opt/ohpc/admin/UAbuild/yambo/yambo-5.0.3/lib/qe_pseudo'
make[1]: *** [yambo] Error 2

**Comment by sangallidavide** [comment]
Dear chrisreidy, we prefer to use the yambo forum before opening new issues.
Please register here: http://www.yambo-code.org/forum/viewforum.php?f=1

Before posting also check if someone already experienced your problem.
Moreover please attach the config.log and the config/report file

I close this issue for now.
