### ISSUE TITLE
yambo web site down

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo#38]
Hi guys, I guess you are aware of this but my link checkers on https://atomistic.software/#/ alerted me to the fact that the yambo web site at https://yambo-code.org/ has been unreachable since at least December 15th.

Worth fixing?

**Comment by sangallidavide** [comment]
Hi Leopold, thanks for the message.

Yeah, the website is not really down, just super slow to load and often it does not load at all.
Apparently, there is an issue with the php installed version and the hosting service.
We are going to fix it today or tomorrow.

**Comment by sangallidavide** [comment]
The yambo website has been moved to a hew hosting.
Please check: https://www.yambo-code.eu
