### ISSUE TITLE
exciton-phonon coupling

### ISSUE THREAD

**Issue by lucamontana** [yambo-code/yambo#4]
Dear developers, 

I was trying to redo the exciton-phonon coupling effect on Si to calculate the temperature-dependent absorption spectrum; However it seems that this is not part of the official release of Yambo as of now. 
Will the exciton-phonon coupling part be released any time soon?

Best,
LUCA

**Comment by sangallidavide** [comment]
Dear Luca, if you refer to the procedure of include the electronic lifetimes in the BSE calculation this should be now fully available in yambo 5.0

This works reasonably well for materials with small binding energy. For materials with strongly bound excitons the procedure has been also applied. However, alternative procedures have been proposed and used in the literature to compute exciton-phonon coupling, which can lead to very different results.
