### ISSUE TITLE
missing separator in compilation

### ISSUE THREAD

**Issue by Odin2111** [yambo-code/yambo#44]
Hello I am struggling with compilation and ending up at the missing separator error. 

```
gcc -traditional -E -P -M -DU77 -DIFC -DGNU       -Isrc/fhp/finc  src/fhp/fsrc/blcomout.F | sed -e 's%blcomout.F.o%blcomout.o %g' | sed -e 's%blcomout.o%sys/ifort/objfst/blcomout.o sys/ifort/objprf/blcomout.o sys/ifort/objdbg/blcomout.o sys/ifort/cpp/blcomout.f sys/ifort/dep/blcomout.d%g' > sys/ifort/dep/blcomout.d
sys/ifort/dep/blcomout.d:3: *** missing separator.  Stop.
```

The make file can be downloaded from link
https://1drv.ms/u/s!AtYtze56Q_P3lFfGtovWp4sLHwlg?e=xNJuMj

**Comment by sangallidavide** [comment]
The user just joined github and the compilation line does not seem to be related to yambo.
I'd suggest not to try to download from the link. I close it for now.
