### ISSUE TITLE
Yambo behaviour when computing EELS/ABS spectra

### ISSUE THREAD

**Issue by palful** [yambo-code/yambo#59]
Following discussions with @sangallidavide, @daniele-varsano, @andrea-ferretti and Savio Laricchia, I am posting this table with the issues and caveats that I have compiled while trying different `Lkind`, `BSEmod`, `BSSmod`, and architecture (GPU/CPU) options.

The last column of the table is written from the perspective of a user who is not familiar with everything behind the scenes (such as how an iterative solver works). 

Some of the issues (such as the scalapack bug or being able to use `BSEmod="coupling"` on GPU) already have a solution/patch/workaround which however is not generally available. 

Other issues may be tackled by changing the logic of the code (such as: if I have `Lfull` I get EELS directly as 1+vX with no inversions/KKR, if I have `Lbar` I get ABS directly as 1-vX with no inversions/KKR).

Finally, some issues are solved by simply telling the user what the code is doing via Warning/Error messages. Particular attention should be given to the cases where the code prints wrong spectra without warning.
  
![Table_solvers](https://github.com/yambo-code/yambo/assets/23454079/f7ae631c-12d5-4150-862f-0009f17efdc8)

**Comment by sangallidavide** [comment]
Fixed with last merge.
