### ISSUE TITLE
2 arguments for YAMBO_FREE while the include file only defines a single argument

### ISSUE THREAD

**Issue by klust** [yambo-code/yambo#6]
https://github.com/yambo-code/yambo/blob/dcccf9b81d47551b1984414546602cd307947705/interfaces/p2y/mod_p2y.F#L325

Preprocessor error since YAMBO_FREE is used here with 2 arguments while include/memory.h defines it with a single argument. I guess this should be two separate calls to YAMBO_FREE.

Which would then result in the same problem as the matching YAMBO_ALLOC calls higher up the subroutine which lack a specific implementation for the generic mem_dri routine.

**Comment by sangallidavide** [comment]
See reply to issue #5
