### ISSUE TITLE
Non ordered G-vectors and energy cutoff

### ISSUE THREAD

**Issue by sangallidavide** [yambo-code/yambo#64]
The G vectors are sorted by doing a loop on the miller indexes, e.g.
(0,0,0), (1,0,0), (0,1,0), (0,0,1), (1,1,0), ...

If the super-cell is non uniform, e.g. suppose z >> (x,y) this implies that this ordering is very different from the ordering as a function of the energy cutoff associated. For example given g1=(100,0,0) and g2=(0,0,100) we will have E[g1] >> E[g2].

In order to perform an integral up to a given cut-off, say 10 Ry (over a maximum of 40 Ry), one needs to find the G vectors which lay inside the corresponding sphere. yambo correctly computes the total number of G-vectors inside such sphere. To this end it  temporary sorts the G-vectors. 
(see sort call here: https://github.com/yambo-code/yambo/blob/master/src/setup/G_shells_finder.F )
Suppose that, as a result, there are 10.000 G (over a total of 200.000) vectors with E< 10 Ry.

Due to the way G-vectors are sorted, this will imply that these G-vectors are not the first 10.000. The sphere:
- would contain some G-vectors with very high index, e.g. vectors g_i=(0,0,N) with very large N
- would not contain some G-vectors with quite low index, e.g. vectors g_j=(m,0,0) with quite small m
This happens because the z direction is much larger in real space, e.g. much smaller in reciprocal space.

Here comes the issue. When doing integrals, the code does not loop over the vectors inside the sphere, but over the vectors from 1 to 10.000. In practice it takes vectors with very high energy in the plane (corresponding cutoff much bigger than 10 Ry) and vectors with very low energy out of plane (corresponding cutoff much smaller than 10 Ry). This implies that, to converge up to a nominal cutoff 10 Ry along z, one would need to set in input a much higher cutoff. Indeed in 2D materials W converges very slowly against the energy cutoff.

There are 2 possible solutions:
a) Create a table which gives the index of the sorted G-vector, say E_sort_g_index, and perform all the integrals in G-space as
```
A=0
do i_g=1,ng_max
  i_g_p=E_sort_g_index(i_g)
  A=A+f(i_g_p)
enddo 
```
b) sort the g-vectors, to avoid changing all G-integrals, and also store the inverse E_sort_g_index for the cases in which the previous sorting is needed.

**Comment by attacc** [comment]
I like more the second solution

**Comment by andreamarini** [comment]
I don't get the problem. Sorry. It may be due to me.

Yambo sums always over all vectors that lay within a sphere. This is because any user defined integer giving the number of G-vectors is replaced with the nearest closed.

Isn't true? Where is the problem then? 

Sorry

**Comment by sangallidavide** [comment]
Yambo sums over all G-vectors from 1 to 10.000, but these are not the ones inside the 10 Ry sphere.

The one inside the sphere have a different ordering.
For example the 5.000 could be outside and the 20.000 could be inside, etc ...
Again, see the call to sort here: https://github.com/yambo-code/yambo/blob/master/src/setup/G_shells_finder.F

**Comment by andreamarini** [comment]
The sort orders the cartesian modulus of the G-vectors to find the shells.

``` 
do ig_1=1,ng_closed
   G_mod(ig_1)=iku_v_norm(g_vec(ig_1,:))
 enddo
 call sort(G_mod,indx=G_mod_indx)
```

Isn't the energy of each vector equal to   ```G_mod(ig_1)**2/2.``` ?

**Comment by andreamarini** [comment]
Let me add the summing over vectors without including all vectors with equal modulus would break the symmetry.

**Comment by sangallidavide** [comment]
> Isn't the energy of each vector equal to G_mod(ig_1)**2/2. ?

Yeah, G_shell_finder does the correct thing.
The problem is how the numbers extracted from from G_shell_fined (e.g. number of g vectors inside a given shell) are used in the code to perform integrals up to a given cutoff.

**Comment by andreamarini** [comment]
Yambo changes the number of plane waves in any sum in the code to be such that it respects the shells. So if you fix the number corresponding to 10Ry yambo will adapt it to have all vectors within the shell nearest to 10Ry.

So it is not possible that a vector respecting that cutoff is not summed.

**Comment by sangallidavide** [comment]
But the vectors with E<10 Ry are not the first 10.000
This is why in G_shell_finder it gets the sort index
```
do ig_1=1,ng_closed
   G_mod(ig_1)=iku_v_norm(g_vec(ig_1,:))
 enddo
 call sort(G_mod,indx=G_mod_indx)
```

So yambo should loop on 
```
di ig=1,10000
  igp=G_mod_indx(ig)
  f(igp)
```
instead it loops on
```
di ig=1,10000
  f(ig)
```

**Comment by andreamarini** [comment]
Davide, this would be a HUGE bug. 

Especially becuase Yambo uses symmetries in the G summations to use the symmetries. And this is possible only if any rotated vector is still in the sum.

Now. I am trying to remember the story of G-vectors from abiinit/pw but I can remember the details now.

Abiinit write g-vectors ordered with increasing modulus. With p2y we had problems as they were not gamma-centered.

I don't remember now how we fixed.

In any case there is no need to change ALL summaltions. It is enough to ensure that the input G-vectors are ordered.

**Comment by andreamarini** [comment]
This is the plot of ```G_mod(ig_1)``` versus ig_1 for two materials of the test-suite that are produced with Abinit and PWscf.

In both cases the G-vectors are correctly ordered.

![test](https://github.com/yambo-code/yambo/assets/25382309/b048423f-4be3-4eb3-9db1-e4415c3f8e20)

**Comment by sangallidavide** [comment]
Yeah, because LiF is cubic, e.g. x=y=z.
Try a 2D material

**Comment by andreamarini** [comment]
Al111 surface

![image](https://github.com/yambo-code/yambo/assets/25382309/4b0ac93f-c139-42cd-b440-ef11c0edb4ca)

**Comment by andreamarini** [comment]
> Davide, this would be a HUGE bug.
> 
> Especially becuase Yambo uses symmetries in the G summations to use the rotate the q vector. And this is possible only if any rotated vector is still in the sum.
> 

![image](https://github.com/yambo-code/yambo/assets/25382309/d9c02980-2417-48b8-ace2-d55a0000f18e)

**Comment by sangallidavide** [comment]
Ok. The database on which I saw the problem is the hBN of the test-suite

![image](https://github.com/yambo-code/yambo/assets/22720887/e50da8a4-4ccc-423d-9b1f-50d43ed110bd)

But it is an old database of abinit. So probably the issue is related to that. Also it is not for all G-vectors, just the last ones. So probably the more recent databases are not affected
