### ISSUE TITLE
Is the EXP integrator formally correct?

### ISSUE THREAD

**Issue by andreamarini** [yambo-code/yambo#93]
In yambo_rt there is one integrator named EXP

` !    2 - Exp integrator:    G(t+dt) = G(t) - i*dt *[H(t'),G(t)] - dt^2 *[H(t'),[H(t'),G(t)]] + ....         [Can be expanded up to order 6]`

that assumes that the n-th derivative of G(t) is obtained by iterating the commutator. 

I attach notes where I demonstrate that this is not the case and additional terms appear. 

Let me know if you agree.

[scan.pdf](https://github.com/yambo-code/yambo/files/15483628/scan.pdf)

**Comment by sangallidavide** [comment]
> that assumes that the n-th derivative of G(t) is obtained by iterating the commutator.

The expansion does not come from "iterating the commutator", but from the expansion of the expression

`exp(+i*H*t) * G(t,t') * exp(-i*H*t)`

There should be notes / papers on this

**Comment by andreamarini** [comment]
The expansion obtained by iterating the commutator is what it is normally used to expand in powers the time-evolution of an operator under the action of a time-independent Hamiltonian.

This is another way to see that the EXP integrator applies **only to static Hamiltonians**

**Comment by attacc** [comment]
Why but I think for short Time steps, It should work
Claudio

Il mer 29 mag 2024, 14:10 Andrea Marini ***@***.***> ha
scritto:

**Comment by andreamarini** [comment]
Claudio, it does not make sense. There is no way to estimate the error induced by neglecting the missing terms. 

It is not a matter of the length of the time step. If the electric field is strong and/or rapid oscillating the result can be arbitrary wrong.

I suggest to remove it.

**Comment by sangallidavide** [comment]
> This is another way to see that the EXP integrator applies **only to static Hamiltonians**

Yeah. It is also written in the description of the subroutine 
![image](https://github.com/yambo-code/yambo/assets/22720887/b6b9cd71-37b4-48b0-aa4d-f49bdf6c4eae)

Still in these cases it is useful.

**Comment by andreamarini** [comment]
Ok. 

I do think it is to be removed because:

a. it is not exact
b. there is no way for any user to realize the limitations

I will clean the RT_integrator in my branch and I will propose a tech branch for that. We will discuss it at the moment of the merging.

**Comment by sangallidavide** [comment]
There are reasons for which the Exp integrator is better than simple Euler for example. e.g. the Exp integrator is unitary.

Some of them are discussed in the paper pointed out by Daniele: https://doi.org/10.1063/1.1774980
If you combine this with RK2, I think you get the "Exponential mid point" discussed in the reference.

Also see the Octopus documentation:
[https://www.octopus-code.org/documentation/13/variables/time-dependent/propagation/](https://www.octopus-code.org/documentation/13/variables/time-dependent/propagation/)

For the user, if he does not know what he is doing, he should not try randomly all the possible propagators, but just stick to the default or to the ones he understands, or study before trying others.

**Comment by andreamarini** [comment]
I provided an exact (simple) derivation.

I believe we should support the coding with more clear math.

- The additional terms can be arbitrary big. 
- Of course it is unitary as it corresponds to the time evolution of a static Hermitian operator. But our Hamiltonian is hermitian but time-dependent.
- Without a clear mathematical derivation that the error can be controlled I think it is too risky to release it at the same level of EULER. Of course the expansion is better for static Hamiltonians (it is just a Taylor expansion). But in the case of time-dependent Hamiltonians while the first order is ok (EULER) the higher terms are wrong.

In any case after re-coding the integration I will check on the validity and report the results in preparation of the merging.

**Comment by sangallidavide** [comment]
Closing issue. The discussion in proceeding here: https://github.com/yambo-code/yambo/issues/95
